### ISSUE TITLE
displayTitle

### ISSUE THREAD

**Issue by Kesse90** [Veldrovive/MMM-Page-Selector#17]
Hi there.
Thank you for this lovely module.
I have this annoying problem, that even though i have set -  displayTitle: false,  - the title of the module on the page is still showed - please see picture.
If i use the other module outside MMM-Page-Selector, the title is gone, so it must be something in page-selector that causes it. :)

Can you guide me? :)

![image](https://user-images.githubusercontent.com/48604632/54520118-3b30ef80-4968-11e9-8b36-0ea68e2e2220.png)

**Comment by Veldrovive** [comment]
I see that you closed this issue. Does that mean that you solved the problem?

If not, can you tell me what version of page-selector you are using? To find this, you can navigate into the MMM-Page-Selector directory and run `git rev-parse --short HEAD`.

**Comment by w19048538** [comment]
Hello, 

Sorry for putting this on a closed issue, but I have the same issue.

The version is: c9c033c
