### ISSUE TITLE
Hiding Third Parties Modules

### ISSUE THREAD

**Issue by Thomallet** [Veldrovive/MMM-Page-Selector#2]
This module is very promising ! However I have difficulties to make it work with external modules. Indeed, when configured, I manage to hide the native modules with no problem, however, 3rd parties modules doesn't hide... Am I missing a configuration step ?

**Comment by Veldrovive** [comment]
That’s odd. As far as I know, magic mirror handles native and 3rd party modules in the same way so there shouldn’t be a difference. If you post your config.js then I can take a look and see if I can figure it out.
Are there any errors in the browser console?

**Comment by Thomallet** [comment]
Thanks from prompt answer. 
Here is an example of my settings with google photo module

```
{
                        module: "MMM-Page-Selector",                         
                        position:"fullscreen_below",
                        config: {
                                defaultPage: "PhotoFrame",
                                displayTitle: false,
                                selectPageNotif: ["SELECT_PAGE"],
                                incrementPageNotif: ["PAGE_UP"],
                                decrementPageNotif: ["PAGE_DOWN"]
                        }
                },
                {
                        module: "MMM-GooglePhotos",
                        position: "fullscreen_below",
                        pages: {Thomas: "fullscreen_below"},
                        config: {
                                albumId: « ID », // your album id from result of `auth_and_t$
                                refreshInterval: 1000*60,
                                scanInterval: 1000*60*10, // too many scans might cause API quota limit also.
                                                        //note(2018-07-29). It is some weird. API documents said temporal image url would li$
                                sort: "time", //'time', 'reverse', 'random'
                                showWidth: "100%", // how large the photo will be shown as. (e.g;'100%' for fullscreen)
                                showHeight: "100%",
                                originalWidthPx: 800, // original size of loaded image. (related with image quality)
                                originalHeightPx: 600, // Bigger size gives you better quality, but can give you network burden.
                                mode: "contain", // "cover" or "contain" (https://www.w3schools.com/cssref/css3_pr_background-size.asp)
                         }
                },
```
The module doesn't hide on the main page...

**Comment by Veldrovive** [comment]
Since native modules seem to work, there is only a couple of things that jump out to me as possibilities. 
First, there could be a glitch with the fullscreen-below position. If you change it so that it displays somewhere else, does it work?
Second, the google photos module may have something that blocks magic mirror from hiding it. This one is doubtful, but I only have my phone for the next couple of days so I can’t actually verify that it isn’t the problem. Try some other module like MMM-astronauts

**Comment by Thomallet** [comment]
I managed to make it work. The default "position" in the modules have to be removed. Doing that the module works perfectly even with third party modules !
Thanks

**Comment by Veldrovive** [comment]
Really? Thank you for catching this. When doing all my testing the position prop was necessary for getting the module to render. As a follow up, what version of MM are you using?

**Comment by Veldrovive** [comment]
I'm going to put a note in the README saying that this is a potential fix for 3rd party modules not hiding. If more information becomes available, feel free to reopen.

**Comment by Omaley** [comment]
Seems that modules doesn't appear when changing pages with my solution... Will try to investigate more...

**Comment by Veldrovive** [comment]
I'm back at my house now so I am capable of doing actual development. If you have any questions or ideas, I will be happy to answer or test them out.

**Comment by Omaley** [comment]
I didn't find a way to make it work with module weatherforecast... Seems that for some plugins like Googlephotos you need to add the position (default) and then precise for pages the position you want. if you do not precise the pages, on my configuration it always shows up while the other modules are not shown. Regarding the weaterforecast, don't find a way to make it disappear on pages. One solution is to put it in background... still working on it but it is strange...

**Comment by Veldrovive** [comment]
I am unable to reproduce any of this behavior. I always have to specify a position prop or else page-selector throws errors since the module wasn't rendered. Weatherforecast takes some time to become visible, but that is just part of the module. Make sure that you are completely restarting Magic Mirror in order to update the pages correctly. What version of Magic Mirror are you running? I tested this module mostly on v2.4.1 so there could potentially be differences to earlier versions.
