### ISSUE TITLE
module incompatibility

### ISSUE THREAD

**Issue by GattoJohnny** [Veldrovive/MMM-Page-Selector#21]
Hi there. I had MMM-LocalTemperature, currentweather, weatherforecast and a few other modules on my mirror. At the same time, on the same page. Actually, on the only page.

After installing MMM-Page-Selector the above mentioned 3 modules have disappeared: MMM-LocalTemperature, currentweather and weatherforecast would not show up.
It seems to me that MMM-LocalTemperature somehow affects the others. If I remove MMM-LocalTemperature from the config file and the rest appear again.
Further observation1: incompatibility is restricted to individual pages. Having MMM-LocalTemperature on Page1 kills currentweather and weatherforecast on Page1, and leaves currentweather and weatherforecast on Page2 intact. (I assume this is normal behavior for MMM-Page-Selector, anyway.)
Further observation2: All these modules are now positioned top_right. However, positions do not matter, MMM-LocalTemperature affects the others regardless of their position.

MM v2.5, MMM-LocalTemperature v1.1.0 with DHT22 sensor on pin 4.

I'm stuck. I'd appreciate if you could give me a hint what to check.

**Comment by Veldrovive** [comment]
With a glance through the MMM-LocalTemperature code, I see a couple of things that might lead to some issues. However, in order for me to really get to the bottom of the problem, it would be helpful to have your specific mirror.
Could you post your config file so I can replicate the environment?

**Comment by GattoJohnny** [comment]
var config = {
	address: "0.0.0.0",
	port: 8081,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.0.1/120", "192.168.0.1/24"],

	language: "hu",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},


		{
			module: 'MMM-Remote-Control',
		},


		{
			module: "MMM-Page-Selector",
			position: "top_center",
			config: {
				defaultPage: "apa",
				displayTitle: false,
				selectPageNotif: ["SELECT_PAGE"],
				incrementPageNotif: ["PAGE_UP"],
				decrementPageNotif: ["PAGE_DOWN"],
				persistentPages: false,
				autoChange: {
//					interval: 9999999
					interval: 15
				}
			}
		},


//		{
//			module: "MMM-Buttons",
//			config: {
//				buttons: [
//					{
//						pin: 24,
//						name: "page_rotation",
//						longPress: {
//							notification: "PAGE_SELECT",
//							payload: "alap"
//						},
//
//
//						shortPress: {
//							notification: "INCREMENT_PAGE",
//						}
//					}
//				],
//				minLongPressTime: 800
//			}
//		},


		{
			module: "clock",
			name: "clock_alap",
			position: "middle_center",
			config: {
				displayType: "analog",
				displaySeconds: "true",
				analogShowDate: "false",
				analogSize: "800px",
				analogFace: "face-002"
			}
		},


		{
			module: 'MMM-CalendarExt',
			name: "calendar_apa",
			position: "top_bar", //anywhere. It is not related to real position of view
			config: {
				system:{
					show: ['weeks'], //daily, weekly, monthly, month, weeks, upcoming, current
					showEmptyView: 1, //1=mutassa akkor is, ha üres
					fullDayEventLocalize: 1, //más időzónák eseményeinek átszámítása sajátra
					redrawInterval: 10*60*1000, //millisec, minimum 60000
					useProfileConfig: 0,
					startProfile: ''
				},

				defaultView: {
					position: 'top_bar',
					positionOrder: -1,
					overflowRolling: 0,
					overflowHeight: 0,
					overflowDuration: 2,
					onlyStartingTime: 0,
					timeFormat: 'H:mm',
					dateFormat: "MMM D.",
					fullDayEventDateFormat: "MMM D.",
					ellipsis: 0, //a cím lerövidítése ennyi karakterre
					limit:0, //ennyi eseményt jelenít meg, 0=korlátlan
					oneLineEvent:0, //0=normál nézet, 1=egysoros nézet
					replaceTitle:[["születésnapja",""]]
				},

				views: {
					month: {
						showWeeks: 1, //a hét számának mutatása
						weeksTitle: 'hét',
						weeksFormat: 'w.', //"https://momentjs.com/docs/#/displaying/format/"
						weekdayFormat: 'dddd',
						titleFormat : 'D',
						overTitleFormat : 'MMM. D.',
						monthTitleFormat: " ",
					},
					weeks: {
						showWeeks: 0, //a hét számának mutatása
						weeksTitle: 'hét',
						weeksFormat: 'w.', //"https://momentjs.com/docs/#/displaying/format/"
						weekdayFormat: 'dddd',
						titleFormat : 'MMM. D.',
						overTitleFormat : 'MMM. D.',
						counts: 2,
					},
					daily: {
						direction: 'row',
						counts: 7, //hány napot mutasson
						titleFormat: "D",
						overTitleFormat: "MMM D",
						subtitleFormat: "ddd",
					},
					weekly: {
						direction: 'row',
						counts: 4,
						titleFormat: "w.",
						overTitleFormat: "gggg. w. hét",
						subtitleFormat: "MMM D.",
					},
					monthly: {
						direction: 'row',
						counts: 3,
						titleFormat: "MMMM",
						overTitleFormat: "YYYY. MMM.",
						subtitleFormat: "YYYY",
					},
					current: {
						title: 'Épp most zajlik',
						useRelative: 1
					},
					upcoming: {
						title: 'Közelgő események',
						useRelative: 0
					},
				},

				defaultCalendar: {
					profiles: [], //[] for all profiles, e.g ['daddy', 'John'] for daddy and John
					views: [],
					symbol: "",
					styleName: "", //There are 20 pre-defined styles in preset.css.(style1 - style20)
					replaceTitle: [],
					maxEntries: 50,
					maxDays: 180,
					interval: 10*60*1000 //millisec
				},

				calendars: [
					{
					name: "InfóTükör",
					url: "xxxx.ics",
					symbol: 'calendar@fa',
					styleName: "style13",
					},

				],
				profileConfigs: {
//					"daddy" : { ... },
				}
			}
		},


		{
			module: "MMM-Futar",
			name: "futar-indulas",
			position: "top_left",
			header: "INDULÁS (Batthyány tér felé)",
			config: {
				stopId: "BKK_F04794",
				routeId: "BKK_6400",
				minutesAfter: 180,
				updateInterval: 30*1000, // milliseconds
				showHead: false, // true | false
				showSymbolInHead: false, // true | false
				showSymbolInStopTime: true, // true | false
				maxNumberOfItems: 4,
				align: "left", // 'left' | 'right'
				fade: false
				}
		},


		{
			module: "MMM-Futar",
			name: "futar-erkezes",
			position: "top_left",
			header: "ÉRKEZÉS (Batthyány tér felől)",
			config: {
				stopId: "BKK_F04793",
				routeId: "BKK_6400",
				minutesAfter: 180,
				updateInterval: 30*1000, // milliseconds
				showHead: false, // true | false
				showSymbolInHead: false, // true | false
				showSymbolInStopTime: true, // true | false
				maxNumberOfItems: 4,
				align: "left", // 'left' | 'right'
				fade: false
				}
		},


		{
			module: "clock",
			name: "clock_apa",
			position: "top_right",
			config: {
				displayType: "digital",
				displaySeconds: false, // #### ki kell venni az idézőjeleket, azokkal nem működik ###
				showDate: false,
				dateFormat: "LL, dddd"
			}
		},


		{
			module: "MMM-LocalTemperature",
			name: "LocalTemperature_apa",
			position: "top_right",
			header: "IDEBENT",
			config: {
				sensorPin: 4,
				updateInterval: 2, // minutes
				units: "metric",
				sendTemperature: true,
				showTemperature: true,
				sendHumidity: true,
				showHumidity: true,
				decimalSymbol: ","
				
				}
		},


		{
			module: "currentweather",
			position: "top_right",
			header: "ODAKINT",			
			config: {
				location: "Budakalász",
				locationID: "3054651",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "ed88dce9dc4ffb49015c1f3a1a78e280",
				updateInterval: 10 * 60 * 1000, // every 10 minutes


				showWindDirection: true,
				showWindDirectionAsArrow: true,
				showHumidity: false,
				showIndoorTemperature: false,
				onlyTemp: false,
				showFeelsLike: false,
				useKMPHwind: true,
				lang: "hu",
				decimalSymbol: ","
			}
		},


		{
			module: "weatherforecast",
			position: "top_right",
			header: "ELŐREJELZÉS:",
			config: {
				location: "Budakalász",
				locationID: "3054651",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "ed88dce9dc4ffb49015c1f3a1a78e280",
				maxNumberOfDays: 5,
				decimalSymbol: ",",
				fade: false,
				showRainAmount: true,
				colored: true
			}
		},

	],


	pages: {
		apa: {
			"calendar_apa": "top_bar",
			"futar-indulas": "top_left",
			"clock_apa": "top_right",
//			"LocalTemperature_apa": "top_right",
			"currentweather": "top_right",
			"weatherforecast": "top_right",
		},

		infotukor: {
			"futar-erkezes": "top_left",
			"LocalTemperature_apa": "top_right",
			"currentweather": "top_right",
			"weatherforecast": "top_right",
		},
	},

	exclusions: [
		"alert",
		"MMM-Buttons",
		"MMM-Remote-Control"
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by GattoJohnny** [comment]
`var config = {
	address: "0.0.0.0",
	port: 8081,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.0.1/120", "192.168.0.1/24"],

	language: "hu",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},


		{
			module: 'MMM-Remote-Control',
		},


		{
			module: "MMM-Page-Selector",
			position: "top_center",
			config: {
				defaultPage: "apa",
				displayTitle: false,
				selectPageNotif: ["SELECT_PAGE"],
				incrementPageNotif: ["PAGE_UP"],
				decrementPageNotif: ["PAGE_DOWN"],
				persistentPages: false,
				autoChange: {
//					interval: 9999999
					interval: 15
				}
			}
		},


//		{
//			module: "MMM-Buttons",
//			config: {
//				buttons: [
//					{
//						pin: 24,
//						name: "page_rotation",
//						longPress: {
//							notification: "PAGE_SELECT",
//							payload: "alap"
//						},
//
//
//						shortPress: {
//							notification: "INCREMENT_PAGE",
//						}
//					}
//				],
//				minLongPressTime: 800
//			}
//		},


		{
			module: "clock",
			name: "clock_alap",
			position: "middle_center",
			config: {
				displayType: "analog",
				displaySeconds: "true",
				analogShowDate: "false",
				analogSize: "800px",
				analogFace: "face-002"
			}
		},


		{
			module: 'MMM-CalendarExt',
			name: "calendar_apa",
			position: "top_bar", //anywhere. It is not related to real position of view
			config: {
				system:{
					show: ['weeks'], //daily, weekly, monthly, month, weeks, upcoming, current
					showEmptyView: 1, //1=mutassa akkor is, ha üres
					fullDayEventLocalize: 1, //más időzónák eseményeinek átszámítása sajátra
					redrawInterval: 10*60*1000, //millisec, minimum 60000
					useProfileConfig: 0,
					startProfile: ''
				},

				defaultView: {
					position: 'top_bar',
					positionOrder: -1,
					overflowRolling: 0,
					overflowHeight: 0,
					overflowDuration: 2,
					onlyStartingTime: 0,
					timeFormat: 'H:mm',
					dateFormat: "MMM D.",
					fullDayEventDateFormat: "MMM D.",
					ellipsis: 0, //a cím lerövidítése ennyi karakterre
					limit:0, //ennyi eseményt jelenít meg, 0=korlátlan
					oneLineEvent:0, //0=normál nézet, 1=egysoros nézet
					replaceTitle:[["születésnapja",""]]
				},

				views: {
					month: {
						showWeeks: 1, //a hét számának mutatása
						weeksTitle: 'hét',
						weeksFormat: 'w.', //"https://momentjs.com/docs/#/displaying/format/"
						weekdayFormat: 'dddd',
						titleFormat : 'D',
						overTitleFormat : 'MMM. D.',
						monthTitleFormat: " ",
					},
					weeks: {
						showWeeks: 0, //a hét számának mutatása
						weeksTitle: 'hét',
						weeksFormat: 'w.', //"https://momentjs.com/docs/#/displaying/format/"
						weekdayFormat: 'dddd',
						titleFormat : 'MMM. D.',
						overTitleFormat : 'MMM. D.',
						counts: 2,
					},
					daily: {
						direction: 'row',
						counts: 7, //hány napot mutasson
						titleFormat: "D",
						overTitleFormat: "MMM D",
						subtitleFormat: "ddd",
					},
					weekly: {
						direction: 'row',
						counts: 4,
						titleFormat: "w.",
						overTitleFormat: "gggg. w. hét",
						subtitleFormat: "MMM D.",
					},
					monthly: {
						direction: 'row',
						counts: 3,
						titleFormat: "MMMM",
						overTitleFormat: "YYYY. MMM.",
						subtitleFormat: "YYYY",
					},
					current: {
						title: 'Épp most zajlik',
						useRelative: 1
					},
					upcoming: {
						title: 'Közelgő események',
						useRelative: 0
					},
				},

				defaultCalendar: {
					profiles: [], //[] for all profiles, e.g ['daddy', 'John'] for daddy and John
					views: [],
					symbol: "",
					styleName: "", //There are 20 pre-defined styles in preset.css.(style1 - style20)
					replaceTitle: [],
					maxEntries: 50,
					maxDays: 180,
					interval: 10*60*1000 //millisec
				},

				calendars: [
					{
					name: "InfóTükör",
					url: "xxxx.ics",
					symbol: 'calendar@fa',
					styleName: "style13",
					},

				],
				profileConfigs: {
//					"daddy" : { ... },
				}
			}
		},


		{
			module: "MMM-Futar",
			name: "futar-indulas",
			position: "top_left",
			header: "INDULÁS (Batthyány tér felé)",
			config: {
				stopId: "BKK_F04794",
				routeId: "BKK_6400",
				minutesAfter: 180,
				updateInterval: 30*1000, // milliseconds
				showHead: false, // true | false
				showSymbolInHead: false, // true | false
				showSymbolInStopTime: true, // true | false
				maxNumberOfItems: 4,
				align: "left", // 'left' | 'right'
				fade: false
				}
		},


		{
			module: "MMM-Futar",
			name: "futar-erkezes",
			position: "top_left",
			header: "ÉRKEZÉS (Batthyány tér felől)",
			config: {
				stopId: "BKK_F04793",
				routeId: "BKK_6400",
				minutesAfter: 180,
				updateInterval: 30*1000, // milliseconds
				showHead: false, // true | false
				showSymbolInHead: false, // true | false
				showSymbolInStopTime: true, // true | false
				maxNumberOfItems: 4,
				align: "left", // 'left' | 'right'
				fade: false
				}
		},


		{
			module: "clock",
			name: "clock_apa",
			position: "top_right",
			config: {
				displayType: "digital",
				displaySeconds: false, // #### ki kell venni az idézőjeleket, azokkal nem működik ###
				showDate: false,
				dateFormat: "LL, dddd"
			}
		},


		{
			module: "MMM-LocalTemperature",
			name: "LocalTemperature_apa",
			position: "top_right",
			header: "IDEBENT",
			config: {
				sensorPin: 4,
				updateInterval: 2, // minutes
				units: "metric",
				sendTemperature: true,
				showTemperature: true,
				sendHumidity: true,
				showHumidity: true,
				decimalSymbol: ","
				
				}
		},


		{
			module: "currentweather",
			position: "top_right",
			header: "ODAKINT",			
			config: {
				location: "Budakalász",
				locationID: "3054651",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "ed88dce9dc4ffb49015c1f3a1a78e280",
				updateInterval: 10 * 60 * 1000, // every 10 minutes


				showWindDirection: true,
				showWindDirectionAsArrow: true,
				showHumidity: false,
				showIndoorTemperature: false,
				onlyTemp: false,
				showFeelsLike: false,
				useKMPHwind: true,
				lang: "hu",
				decimalSymbol: ","
			}
		},


		{
			module: "weatherforecast",
			position: "top_right",
			header: "ELŐREJELZÉS:",
			config: {
				location: "Budakalász",
				locationID: "3054651",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "ed88dce9dc4ffb49015c1f3a1a78e280",
				maxNumberOfDays: 5,
				decimalSymbol: ",",
				fade: false,
				showRainAmount: true,
				colored: true
			}
		},

	],


	pages: {

		apa: {
			"calendar_apa": "top_bar",
			"futar-indulas": "top_left",
			"clock_apa": "top_right",
//			"LocalTemperature_apa": "top_right",
			"currentweather": "top_right",
			"weatherforecast": "top_right",
		},

		infotukor: {
			"futar-erkezes": "top_left",
			"LocalTemperature_apa": "top_right",
			"currentweather": "top_right",
			"weatherforecast": "top_right",
		},
	},

	exclusions: [
		"alert",
		"MMM-Buttons",
		"MMM-Remote-Control"
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by GattoJohnny** [comment]
[config.js.txt](https://github.com/Veldrovive/MMM-Page-Selector/files/3203188/config.js.txt)

**Comment by GattoJohnny** [comment]
Any hints?

**Comment by Veldrovive** [comment]
Sorry, I'm a bit busy with some summer courses.
I don't seem to be able to replicate your issue. Could you use the `git rev-parse --short HEAD` command in the MMM-Page-Selector folder to find exactly which version you are using? Your config syntax is a bit behind the current version so the issue might be due to an old version of the module.

**Comment by GattoJohnny** [comment]
D
03b875e

**Comment by Veldrovive** [comment]
Ok, on that version, the exclusions should be an object that follows the same format as the pages objects instead of an array. However, even with that issue, the module should function correctly and I am still unable to replicate your problem. 
What OS are you running the mirror on and are you running in server only mode or electron app mode?

**Comment by GattoJohnny** [comment]
It is MM 2.5 on RPi3B+. I chose the automatic installation with the curl command in the bash script, so I guess it is Electron.
I'm gonna give v2.7 a try with the most up to date MMM-Page-Selector soon. Will keep you posted. And a big thanks for your commitment and excellent assistance.

**Comment by GattoJohnny** [comment]
MM v2.7.1 and MMM-Page-Selector 03b875e (whatever this means) works fine with MMM-LocalTemperature, currentweather and weatherforecast.
So far so good but needs some more investigation on my side. I keep on testing with further modules being present when the problem occurred.
