### ISSUE TITLE
Select page

### ISSUE THREAD

**Issue by ErasmoMMM** [Veldrovive/MMM-Page-Selector#25]
Hello! Sorry for my bad. I have a small problem. The module just lets me change the page by clicking on the indicator the first time. When the page changes, the option disappears and I cannot click the mouse again. This is my configuration:
``` js
{
        module: 'MMM-page-indicator',
        position: 'bottom_bar',
        config: {
            pages: 5,
        }
    }, 
```
Muchas gracias por adelantado!

**Comment by Veldrovive** [comment]
Hey,
My bad for not knowing Spanish.

I suspect that there is a problem with another part of the `config.js`.
The fix will depend on which method you are using to define pages. If pages are defined inline with the modules as outlined [here](https://github.com/Veldrovive/MMM-Page-Selector#there-are-two-options-for-creating-pages-if-in-doubt-use-the-first-one) then your `MMM-page-indicator` config should look like this:
``` js
{
    module: "MMM-page-indicator",
    pages: {"all": "bottom_bar"}
}
```
(P.S. You don't need to define how many pages you have, `MMM-page-selector` interacts with `MMM-page-indicator` and handles that automatically)


If you are the second method as outlined [here](https://github.com/Veldrovive/MMM-Page-Selector#the-second-method-for-defining-pages) then you will need to define an `exclusions` prop in the root of your config like so:
``` js
exclusions: {
    "MMM-page-indicator": "bottom_bar"
}
```

**Comment by ErasmoMMM** [comment]
Good morning and thanks for your interest. I have made some changes to my config.js leaving it like this in regard to the subject:

modules: [
	{
        module: "MMM-page-indicator",
	},
        {
	module: 'MMM-pages',
        config: {
                modules:
                   [
		//  Página principal - PRINCIPAL
		       ["updatenotification", "MMM-UVIndex", "MMM-AirQuality", "MMM-Tools", "compliments", "weatherforecast"],
	        // Segunda página - NOTICIAS
                       ["newsfeed", "MMM-MotionDetector", "MMM-network-signal"],
		//  Tercera página - PERSONAL
        	       ["MMM-GooglePhotos", "MMM-GoogleFit", "MMM-GoogleFit2"],
		//  Cuarta página - CANTERAS/GÁLDAR/MADRID
                       ["calendar", "MMM-DarkSkyForecast", "MMM-EmbedYoutube"],	
		//  Quinta página - UD LAS PALMAS
		       ["MMM-BackgroundSlideshow", "MMM-SimpleLogo", "MMM-Widget", "MMM-NewsFeedTicker"],
		   ],
                fixed: ["MMM-TelegramBot", "MMM-ImageSlideshow", "MMM-LocalTemperature", "MMM-WeatherDependentClothes", "alert", "MMM-Cursor", "clock", "currentweather", "MMM-GroveGestures", "MMM-page-indicator"],
        	exclusions: {"MMM-page-indicator": "bottom_bar"},
		animationTime: "3000",
		rotationTime: "60000",
		delayTime: "180000"
	}
   },

And the end of config.js I left it like this:

{
        module: 'MMM-page-indicator',
        position: 'bottom_bar',
	pages: {"all": "bottom_bar"},
        config: {
          //  pages: 5,
        }
    }, 

I see that something better works but it still does not work properly. When I select a page, it is very difficult to let me select another with the mouse. What am I doing wrong?

Thanks again in advance.

**Comment by Veldrovive** [comment]
Oh, haha. You are using `MMM-pages`, not `MMM-Page-Selector`. I'm not exactly sure how this would work with `MMM-pages`, but for help, you should post [here](https://github.com/edward-shen/MMM-pages/issues).
For `MMM-Page-Selector`, I would suggest a config like this:
``` js
modules: [
	{
		module: "MMM-Page-Selector",
		position: "top_bar", // You must have this position defined
		config: {
			defaultPage: "PRINCIPAL",
			displayTitle: true,
			autoChange: {
	    	        	interval: 60
	    		}
		}
	},
	...
	{
		module: "newsfeed",
		// No position neccesary here
		config: {
			...
		}
	},
	...
	{
		module: "MMM-page-indicator",
		// No position neccesary
		config: {
			// No need to define how many pages you have
		}
	}
],
pages: {
	"PRINCIPAL": {
		"updatenotification": "YOUR_LOCATION",
		"MMM-UVIndex": "YOUR_LOCATION",
		"MMM-AirQuality": "YOUR_LOCATION",
		"MMM-Tools": "YOUR_LOCATION",
		"compliments": "YOUR_LOCATION",
		"weatherforecast": "YOUR_LOCATION"
	},
	"NOTICIAS": {
		... // Fill in the modules you wish to appear on this page
	},
	"PERSONAL": {
		...
	},
	"CANTERAS/GÁLDAR/MADRID": {
		...
	},
	"UD LAS PALMAS": {
		...
	}
},
exclusions: {
	"MMM-page-indicator": "bottom_bar"
}
```

If you don't want the ability to change the position of your modules on different pages, I would suggest using `MMM-pages`. If you want more control, use `MMM-Page-Selector`. They both solve similar problems.

**Comment by ErasmoMMM** [comment]
Ha ha ha ... I already said that something did not fit me !! Thank you very much for your time and interest and excuse my confusion. I will try the settings you indicate with MMM-Page-Selector. Thank you!!

**Comment by Veldrovive** [comment]
I'll assume that you have worked out what you will be doing.
