### ISSUE TITLE
adding pagename to PAGE_CHANGED notification

### ISSUE THREAD

**Issue by rafhtl** [Veldrovive/MMM-Page-Selector#28]
Thank you for the great work!!!
could you add in line 166
self.sendNotification("PAGE_CHANGED", {pagenumber: indexOfPage, pagename: pageName});

I understand that this is not compatible with Integration with MMM-page-indicator
but this would be really useful
maybe there is a better way or a distinct sendnotification for current_page_name?

thankyou

**Comment by Veldrovive** [comment]
While I can't change the `PAGE_CHANGED` notification, I added a new notification `PAGE_UPDATE` that includes the keys `index` and `name`.
