### ISSUE TITLE
There is always an emty page

### ISSUE THREAD

**Issue by keineAhnung667** [Veldrovive/MMM-Page-Selector#36]
Hello,
I just started using your module and really like it. But there is one thing i dont like and maybe there is a workaround:

When im switching between the pages using another module to send notifications like "INCREMENT_PAGE" there is always an emty page at the end instead of starting from the beginning.

Here is my config:

> 	{
>         module: "MMM-Page-Selector",
>         position: "top_bar",
>         config: {
>             //defaultPage: "Page1",
>             displayTitle: true,
>             selectPageNotif: ["SELECT_PAGE"],
>             incrementPageNotif: ["PAGE_UP"],
>             decrementPageNotif: ["PAGE_DOWN"],
> 			//autoChange: {
> 	    	//interval: 10
> 			//}
>         }
>     },
> 	],
> 	
> 	pages: {
>     Page1: {
>     "MMM-WeatherChart": "top_right",
> 	"MMM-Fuel": "bottom_left",
> 	"newsfeed": "bottom_center"
>     },
>     Page2: {
>     "MMM-DarkSkyForecast": "top_right",
> 	"MMM-DWD-WarnWeather": "bottom_left"
>     }
> 	},
> 
> 	exclusions: {
> 		"clock": "top_left",
> 		"MMM-OnScreenMenu": "bottom_right"
> 	},

When i skip through my pages with "INCREMENT_PAGE" there is first "Page1", then "Page2" and then there is an emty page only with my excluded modules and its called "No Page Selected".
Is there a way to skip this page and start with "Page1" again?

Thanks.

**Comment by Veldrovive** [comment]
Hmm, that is not intended behavior. It should never have a page with just exclusions.
I see this same bug in my test environment, so I must have introduced it in a recent change. I'll get that fixed for you.

**Comment by Veldrovive** [comment]
Ah, I see. This bug occurs when the default page is set to an empty string. When the page array is constructed, it finds that the current page does not exist so it adds it.

That issue should now be fixed. If you don't select a default page, one will be selected from the list. Pull the newest changes to get this update.
