### ISSUE TITLE
restoreDefault question

### ISSUE THREAD

**Issue by ReD1470** [Veldrovive/MMM-Page-Selector#37]
Hi Fan's of this nifty module,

As i'm working my way to update my current mirror, with a physical button to cycle through 2-3 pages, I'm stumbeling with the parameter restoreDefault.
Long story short. it doesn't fall back to the defaultpage after 10 seconds.
It is responding perfectly to the key binding option. But does not come back to the default page.
Because the parameter is restoreDefault: integer, I tried with and without "", no luck.
What is my tired old brain missing?

here's the config
```
 {
                        module: "MMM-Page-Selector",
                        position: "top_center",
                        config: {
                            defaultPage: "main",
                            displayTitle: true,
                            selectPageNotif: ["SELECT_PAGE"],
                            incrementPageNotif: ["PAGE_UP"],
                            decrementPageNotif: ["PAGE_DOWN"],
                            persistentPages: false,
                            restoreDefault: 10
                        }
                    },
```

**Comment by Veldrovive** [comment]
I honestly don't even remember introducing this functionality. I don't think it gets used much.
Looking at the code, what you have in your example config should work.

Let me get a test environment spun up and I'll get this solved.

**Comment by Veldrovive** [comment]
It seems to be working fine for me. To debug further I would need more of your config file.

The most likely cause of this would be an incorrect default page name. Are you sure that one of your pages is named "main"? Capitalization is ignored btw.

**Comment by ReD1470** [comment]
WOW you're a quick one arent't ye. tnx!
well here is the whole test config I have so far.

[config.zip](https://github.com/Veldrovive/MMM-Page-Selector/files/5928696/config.zip)

**Comment by Veldrovive** [comment]
Well, it's this or course work and I'm a bit burned out.

Also, this issue should not be fixed. It was an oversight when I added new ways to switch pages. Just pull the new version and it should be fixed.

If everything is fixed, please close this issue.

**Comment by Veldrovive** [comment]
Also, you should definitely use an integer value for `restoreDefault`. It's what's expected. I think it works with a string anyways, but that's undefined behavior.

**Comment by ReD1470** [comment]
I do not know if you like beer, but you earned one. It's working! 
Cheers Mate! and thx again for the quick response.
