### ISSUE TITLE
Autoswitching between Pages

### ISSUE THREAD

**Issue by MunichStef** [Veldrovive/MMM-Page-Selector#4]
I was wondering if you'd be able to add an option to automatically switch the pages from one to another.
You could add an option in the settings with the defined time in seconds for changing pages. If the time is set to 0 (=default) no autoswitching is performed.

**Comment by Veldrovive** [comment]
I like it. I'm currently refactoring my code to reduce the complexity introduced in recent updates and I'll add this while I'm at it.

**Comment by Veldrovive** [comment]
Ok, a very simple method of autoswitching has been added. Refer to [these](https://github.com/Veldrovive/MMM-Page-Selector#usage) [two](https://github.com/Veldrovive/MMM-Page-Selector#configuration) sections of the readme for more info.

**Comment by MunichStef** [comment]
wow...that was really quick Thanks a lot!
