### ISSUE TITLE
Terms of Use, License

### ISSUE THREAD

**Issue by bachoo786** [Veldrovive/MMM-Page-Selector#44]
Hi there

thank you for this amazing module, I wanted to know the terms of use of this module and if there is any licensing involved? I have modified the module for my own needs as a stand alone display and not running in a mirror etc.

I am thinking of commercialising my product and wanted to know the terms and conditions involved please. Kindly let me know.

Many thanks.

**Comment by Veldrovive** [comment]
I've added an MIT license. I apologize for not seeing your messages earlier. I have been out of the world of open source this last year.

**Comment by bachoo786** [comment]
Thank you @Veldrovive
