### ISSUE TITLE
Switch pages with a button

### ISSUE THREAD

**Issue by Robiv8** [Veldrovive/MMM-Page-Selector#7]
Hello Veldrovive,
I would like to switch pages with a real physical button.
I have 4 buttons available and I want button 1 on the main page and then button 2 on the second page and so on.

I have already installed the module button.
Can you give me a hint how to get started?

Thank you

**Comment by Veldrovive** [comment]
Ok, so you can use the notification system to do this. Here is an example of how it will work:
I am following the format given on the [MMM-Buttons readme](https://github.com/Jopyth/MMM-Buttons)
```js
buttons: [
            {
                pin: 0, //The pin that connects your first button
                name: "Main Page Button", //Or whatever you really want
                longPress: { //longPress or shortPress doesnt matter. Really it's just the stuff on the inside that matters.
                    notification: "PAGE_SELECT",
                    payload: "main" //Or whatever page you want
                },
                shortPress: {
                    notification: "PAGE_SELECT",
                    payload: "main" //Or whatever page you want
                }
            },
           ... //Then just use the same thing for your other buttons, just change the page name
        ]
```
I think that should work. I don't have access to something I can really test this with right now, but theoretically that is correct.

**Comment by Robiv8** [comment]
Great! Many thanks for the impulse, will test it.
